"""
Webhook manager constants.
"""

WEBHOOK_NAME_MAX_LENGTH = 80
USERNAME_OVERRIDE_MAX_LENGTH = 80
MAX_EMBEDS_PER_MESSAGE = 10
TOKEN_BYTES = 48
SIGNATURE_HEADER = "X-Plexichat-Signature"
SIGNATURE_TIMESTAMP_HEADER = "X-Plexichat-Timestamp"
SIGNATURE_VERSION = "v1"
