#!/usr/bin/env python3
import secrets
from pathlib import Path


ROOT = Path("/workspace")
ENV_PATH = ROOT / ".env.generated"
BACKEND_CONFIG_PATH = ROOT / "config" / "docker-config.yaml"
CLIENT_RUNTIME_PATH = Path("/workspace-client-runtime") / "client-config.js"


def rand_hex(nbytes: int = 32) -> str:
    return secrets.token_hex(nbytes)


def load_env(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        data[k.strip()] = v.strip()
    return data


def write_env(path: Path, env: dict[str, str]) -> None:
    lines = [
        "# Auto-generated by docker/bootstrap/bootstrap.py",
        "# Safe to keep locally. Do NOT commit.",
    ]
    for k in sorted(env.keys()):
        lines.append(f"{k}={env[k]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ensure_env() -> dict[str, str]:
    env = load_env(ENV_PATH)
    defaults = {
        "POSTGRES_DBNAME": "plexichat",
        "POSTGRES_USER": "plexichat",
        "POSTGRES_PASSWORD": rand_hex(24),
        "POSTGRES_HOST": "db",
        "POSTGRES_PORT": "5432",
        "POSTGRES_SSLMODE": "disable",
        "REDIS_PASSWORD": rand_hex(24),
        "REDIS_HOST": "redis",
        "REDIS_PORT": "6379",
        "MINIO_ROOT_USER": "plexichat",
        "MINIO_ROOT_PASSWORD": rand_hex(24),
        "S3_BUCKET": "plexichat-media",
        "S3_REGION": "us-east-1",
        "S3_ACCESS_KEY": "plexichat",
        "S3_SECRET_KEY": rand_hex(24),
        "S3_ENDPOINT": "http://minio:9000",
        "S3_PUBLIC_URL": "",
        "PLEXICHAT_SYSTEM_KEY": rand_hex(32),
        "PLEXICHAT_MESSAGE_KEY": rand_hex(32),
        "PLEXICHAT_MEDIA_KEY": rand_hex(32),
        "PLEXICHAT_SMTP_PASSWORD": "",
        "LOG_LEVEL": "INFO",
        "MONITORING_ENABLED": "true",
        "MONITORING_METRICS_ENABLED": "true",
        "NO_STRICT_CONFIG": "false",
    }
    for k, v in defaults.items():
        env.setdefault(k, v)
    write_env(ENV_PATH, env)
    return env


def write_backend_config(env: dict[str, str]) -> None:
    BACKEND_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = f"""application:
  name: Plexichat
  environment: production

server:
  host: 0.0.0.0
  port: 8000
  workers: 1
  reload: false

logging:
  level: {env["LOG_LEVEL"]}
  include_exception_details: false

database:
  type: postgres
  postgres:
    host: {env["POSTGRES_HOST"]}
    port: {env["POSTGRES_PORT"]}
    user: {env["POSTGRES_USER"]}
    password: {env["POSTGRES_PASSWORD"]}
    dbname: {env["POSTGRES_DBNAME"]}
    sslmode: {env["POSTGRES_SSLMODE"]}

redis:
  enabled: true
  host: {env["REDIS_HOST"]}
  port: {env["REDIS_PORT"]}
  password: {env["REDIS_PASSWORD"]}
  db: 0
  ssl: false

authentication:
  encryption:
    require_secure_source: true
    media_key: "{env["PLEXICHAT_MEDIA_KEY"]}"

media:
  storage_backend: s3
  data_dir: /root/.plexichat/data
  logs_dir: /root/.plexichat/logs
  media_dir: /root/.plexichat/media
  temp_dir: /root/.plexichat/temp
  s3_bucket: {env["S3_BUCKET"]}
  s3_access_key: {env["S3_ACCESS_KEY"]}
  s3_secret_key: {env["S3_SECRET_KEY"]}
  s3_region: {env["S3_REGION"]}
  s3_endpoint: {env["S3_ENDPOINT"]}
  s3_public_url: "{env["S3_PUBLIC_URL"]}"

api:
  trust_x_forwarded_for: true
  trusted_proxies:
    - client

docs:
  enabled: true
  path: /docs

admin_ui:
  enabled: true
  path: /admin

monitoring:
  enabled: true
"""
    BACKEND_CONFIG_PATH.write_text(content, encoding="utf-8")


def write_client_runtime_config() -> None:
    CLIENT_RUNTIME_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = """window.PLEXICHAT_CONFIG = {
  serverUrl: '',
  hideServerField: true,
  defaultTheme: 'ocean',
};
"""
    CLIENT_RUNTIME_PATH.write_text(content, encoding="utf-8")


def main() -> None:
    env = ensure_env()
    write_backend_config(env)
    write_client_runtime_config()
    print("Bootstrap complete: repo-local env and docker configs ready.")


if __name__ == "__main__":
    main()
