"""
Configuration schemas for API responses.
"""

from pydantic import BaseModel, Field
from typing import List


class AvatarConfigResponse(BaseModel):
    """Avatar configuration details."""

    default_colors: List[str] = Field(
        ..., description="The color palette for autogenerated avatars"
    )
    max_size: int = Field(
        ..., description="Maximum allowed dimension for avatars (width/height)"
    )
    max_file_size: int = Field(..., description="Maximum allowed file size in bytes")
    allowed_types: List[str] = Field(
        ..., description="List of allowed MIME types for avatars"
    )


class ServerCapabilitiesResponse(BaseModel):
    """Global server capabilities and configuration."""

    avatars: AvatarConfigResponse
    access_token_required: bool = Field(
        False, description="Whether API access tokens are required"
    )
    # Future expansion:
    # messaging: Optional[MessagingConfigResponse]
    # voice: Optional[VoiceConfigResponse]
