from typing import Any, Optional, Dict

from ...base import SnowflakeID
from ..models import VoiceState, VoiceChannel


class VoiceProtocol:
    _db: Any = None
    _auth: Any = None
    _servers: Any = None
    _relationships: Any = None
    _presence: Any = None

    def _get_timestamp(self) -> int: ...
    def _generate_id(self) -> int: ...
    def _user_exists(self, user_id: SnowflakeID) -> bool: ...

    def _validate_user(self, user_id: SnowflakeID) -> None: ...
    def _get_server_channel(
        self, channel_id: SnowflakeID
    ) -> Optional[Dict[str, Any]]: ...
    def _is_voice_channel(self, channel_type: str) -> bool: ...
    def _check_permission(
        self,
        user_id: SnowflakeID,
        server_id: SnowflakeID,
        permission: str,
        channel_id: Optional[SnowflakeID] = None,
    ) -> bool: ...
    def _require_permission(
        self,
        user_id: SnowflakeID,
        server_id: SnowflakeID,
        permission: str,
        channel_id: Optional[SnowflakeID] = None,
    ) -> None: ...
    def _get_channel_user_count(self, channel_id: SnowflakeID) -> int: ...
    def _get_channel_settings(self, channel_id: SnowflakeID) -> Dict[str, Any]: ...
    def _ensure_channel_settings(self, channel_id: SnowflakeID) -> None: ...
    def _row_to_voice_state(self, row: Dict[str, Any]) -> VoiceState: ...
    def _row_to_voice_channel(
        self, channel_row: Dict[str, Any], settings: Dict[str, Any]
    ) -> VoiceChannel: ...

    def get_voice_state(self, user_id: SnowflakeID) -> Optional[VoiceState]: ...
    def get_voice_channel(
        self, channel_id: SnowflakeID, user_id: SnowflakeID
    ) -> Optional[VoiceChannel]: ...
    def move_member(
        self,
        moderator_id: SnowflakeID,
        target_user_id: SnowflakeID,
        channel_id: SnowflakeID,
    ) -> VoiceState: ...
    def get_stage(self, channel_id: SnowflakeID) -> Optional[Any]: ...
