import re
from typing import Any, Optional, Protocol

import utils.logger as logger

from .. import dialect
from .types import DbConnection, DbCursor


class _DatabaseMaintenanceProtocol(Protocol):
    type: str
    _local: Any
    monitor: Any

    @property
    def transaction_depth(self) -> int: ...

    @transaction_depth.setter
    def transaction_depth(self, value: int) -> None: ...

    @property
    def in_transaction(self) -> bool: ...

    @in_transaction.setter
    def in_transaction(self, value: bool) -> None: ...

    def get_correlation_id(self) -> Optional[str]: ...
    def fetch_one(
        self, query: str, params: Optional[tuple] = None
    ) -> Optional[dict]: ...
    def fetch_all(self, query: str, params: Optional[tuple] = None) -> list: ...
    def execute(self, query: str, params: Optional[tuple] = None) -> None: ...
    def table_exists(self, table: str) -> bool: ...
    def column_exists(self, table: str, column: str) -> bool: ...
    def index_exists(self, index_name: str) -> bool: ...
    def _sanitize_identifier(self, identifier: str) -> str: ...


class DatabaseMaintenanceMixin:
    def _validate_transaction_state(self):
        if self.type == "postgres" and hasattr(self._local, "connection"):  # pyright: ignore[reportAttributeAccessIssue]
            conn = self._local.connection  # pyright: ignore[reportAttributeAccessIssue]
            try:
                with conn.cursor() as cursor:
                    cursor.execute("SELECT 1")
            except Exception as e:
                err_msg = str(e)
                pg_code = getattr(e, "pgcode", None)

                is_failed = (
                    "InFailedSqlTransaction" in type(e).__name__
                    or pg_code == "25P02"
                    or "current transaction is aborted" in err_msg.lower()
                )

                if is_failed:
                    logger.warning(
                        f"Detected failed transaction state ({err_msg}), recovering..."
                    )
                    try:
                        conn.rollback()
                        logger.info(
                            "Successfully recovered from failed transaction state"
                        )
                    except Exception as rb_e:
                        logger.error(
                            f"Failed to recover from transaction error: {rb_e}"
                        )
                    finally:
                        self.transaction_depth = 0
                        self.in_transaction = False

    def _handle_execution_error(
        self,
        conn: DbConnection,
        cursor: DbCursor,
        e: Exception,
        query: str,
    ):
        error_type = type(e).__name__
        logger.error(f"Query failed ({error_type}): {str(e)[:100]}")

        try:
            if self.type == "postgres":  # pyright: ignore[reportAttributeAccessIssue]
                if conn and getattr(conn, "closed", 0) > 0:
                    self.transaction_depth = 0
                    self.in_transaction = False
                elif conn and self.transaction_depth > 0:
                    try:
                        if cursor is not None:
                            cursor.execute(
                                f"ROLLBACK TO SAVEPOINT sp_{self.transaction_depth}"
                            )
                    except Exception:
                        conn.rollback()
                        self.transaction_depth = 0
                        self.in_transaction = False
                elif conn:
                    conn.rollback()
                    self.in_transaction = False
            elif conn and not self.in_transaction:
                conn.rollback()
        except Exception as cleanup_e:
            logger.error(f"Error during error cleanup: {cleanup_e}")
        finally:
            if cursor is not None:
                cursor.close()

    def convert_schema(self, schema: str) -> str:
        """Convert a SQLite-authored schema into a PostgreSQL-compatible one.

        The codebase writes a single canonical schema string in SQLite dialect
        (the form used in every ``src/core/*/schema.py`` file) and converts
        it to PostgreSQL on demand via this function. SQLite is permissive
        about type names (it stores everything as one of five affinities)
        so most of the schema already works verbatim, but a handful of
        SQLite-specific constructs need to be rewritten:

        * ``BLOB`` -> ``BYTEA`` (PostgreSQL binary type).
        * ``INTEGER`` -> ``BIGINT`` (PostgreSQL has no 32-bit integer;
          snowflake IDs require 64-bit).
        * ``INTEGER PRIMARY KEY AUTOINCREMENT`` -> ``BIGINT PRIMARY KEY
          GENERATED BY DEFAULT AS IDENTITY`` (PostgreSQL's standard
          autoincrement form). We deliberately don't use ``SERIAL`` so
          the column accepts explicit IDs (snowflakes) and so the
          generated type matches the BIGINT we use elsewhere.
        * ``BOOLEAN DEFAULT 0/1`` -> ``BOOLEAN DEFAULT FALSE/TRUE``
          (PostgreSQL rejects 0/1 as boolean defaults; the cast still
          accepts them as input values).
        * ``TIMESTAMP`` -> ``TIMESTAMP`` (already portable; kept here as
          a no-op anchor for future changes).

        The conversions are intentionally surgical so they only target
        type names and a few well-defined constructs, not the contents
        of string literals or comments.
        """
        if self.type != "postgres":  # pyright: ignore[reportAttributeAccessIssue]
            return schema

        import re

        converted = schema

        # BLOB -> BYTEA (must run before INTEGER to keep word boundaries clean)
        converted = re.sub(r"\bBLOB\b", "BYTEA", converted, flags=re.IGNORECASE)

        # INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT PRIMARY KEY GENERATED ...
        # We rewrite the autoincrement column shape to PostgreSQL's identity
        # syntax, then let the generic INTEGER -> BIGINT pass upgrade any
        # remaining INTEGER column types.
        converted = re.sub(
            r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
            "BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY",
            converted,
            flags=re.IGNORECASE,
        )

        # Any remaining bare INTEGER -> BIGINT. This is safe because the
        # INTEGER -> BIGINT upgrade matches word boundaries and the
        # codebase doesn't use 32-bit specific semantics anywhere.
        converted = re.sub(r"\bINTEGER\b", "BIGINT", converted, flags=re.IGNORECASE)

        # BOOLEAN DEFAULT 0/1 -> BOOLEAN DEFAULT FALSE/TRUE
        converted = re.sub(
            r"\bBOOLEAN\s+DEFAULT\s+0\b",
            "BOOLEAN DEFAULT FALSE",
            converted,
            flags=re.IGNORECASE,
        )
        converted = re.sub(
            r"\bBOOLEAN\s+DEFAULT\s+1\b",
            "BOOLEAN DEFAULT TRUE",
            converted,
            flags=re.IGNORECASE,
        )

        return converted

    def _sanitize_identifier(self, identifier: str) -> str:
        return dialect.sanitize_identifier(identifier, self.type)  # pyright: ignore[reportAttributeAccessIssue]

    def _convert_placeholders(self, query: str) -> str:
        return dialect.convert_placeholders(query, self.type)  # pyright: ignore[reportAttributeAccessIssue]

    def _check_connection_age(self, conn_id: int):
        self.monitor.check_connection_age(conn_id)  # pyright: ignore[reportAttributeAccessIssue]

    def _format_log_context(self, **kwargs) -> str:
        ctx = [f"{k}={v}" for k, v in kwargs.items()]
        correlation_id = self.get_correlation_id()  # pyright: ignore[reportAttributeAccessIssue]
        if correlation_id:
            ctx.append(f"correlation_id={correlation_id}")
        return f"[{' '.join(ctx)}]"

    def table_exists(self, table_name: str) -> bool:
        """
        Check if a table exists in the database.

        Args:
            table_name: Name of the table to check

        Returns:
            True if table exists, False otherwise
        """
        if not re.match(r"^[a-zA-Z0-9_]+$", table_name):
            logger.warning(f"Invalid table name for existence check: {table_name}")
            return False

        if self.type == "postgres":  # pyright: ignore[reportAttributeAccessIssue]
            row = self.fetch_one(  # pyright: ignore[reportAttributeAccessIssue]
                "SELECT 1 FROM information_schema.tables WHERE table_name = ?",
                (table_name,),
            )
            return row is not None
        else:
            row = self.fetch_one(  # pyright: ignore[reportAttributeAccessIssue]
                "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
                (table_name,),
            )
            return row is not None

    def column_exists(self, table_name: str, column_name: str) -> bool:
        """
        Check if a column exists in a table.

        Args:
            table_name: Name of the table
            column_name: Name of the column

        Returns:
            True if column exists, False otherwise
        """
        if not re.match(r"^[a-zA-Z0-9_]+$", table_name) or not re.match(
            r"^[a-zA-Z0-9_]+$", column_name
        ):
            logger.warning(
                f"Invalid table/column name for existence check: {table_name}.{column_name}"
            )
            return False

        if not self.table_exists(table_name):
            return False

        if self.type == "postgres":  # pyright: ignore[reportAttributeAccessIssue]
            row = self.fetch_one(  # pyright: ignore[reportAttributeAccessIssue]
                "SELECT 1 FROM information_schema.columns WHERE table_name = ? AND column_name = ?",
                (table_name, column_name),
            )
            return row is not None
        else:
            safe_table = self._sanitize_identifier(table_name)
            rows = self.fetch_all(f"PRAGMA table_info({safe_table})")  # pyright: ignore[reportAttributeAccessIssue]
            return any(row["name"] == column_name for row in rows)

    def index_exists(self, index_name: str) -> bool:
        """
        Check if an index exists in the database.

        Args:
            index_name: Name of the index to check

        Returns:
            True if index exists, False otherwise
        """
        if not re.match(r"^[a-zA-Z0-9_]+$", index_name):
            logger.warning(f"Invalid index name for existence check: {index_name}")
            return False

        if self.type == "postgres":  # pyright: ignore[reportAttributeAccessIssue]
            row = self.fetch_one(  # pyright: ignore[reportAttributeAccessIssue]
                "SELECT 1 FROM pg_indexes WHERE indexname = ?",
                (index_name,),
            )
            return row is not None
        else:
            row = self.fetch_one(  # pyright: ignore[reportAttributeAccessIssue]
                "SELECT name FROM sqlite_master WHERE type='index' AND name=?",
                (index_name,),
            )
            return row is not None
