from typing import Any, Dict, Optional
from enum import Enum

class MalformedConfigAction(Enum):
    CRASH_ON_SINGLE = ...
    CRASH_ON_MANY = ...
    IGNORE = ...

class ConfigLoader:
    config: Dict[str, Any]
    def __init__(
        self,
        config_path: str,
        default_config: Optional[Dict[str, Any]] = None,
        malformed_action: MalformedConfigAction = MalformedConfigAction.CRASH_ON_SINGLE,
    ) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_all(self) -> Dict[str, Any]: ...

_config_instance: Optional[ConfigLoader] = ...
_setup_called: bool = ...

def setup(
    config_path: str,
    default_config: Optional[Dict[str, Any]] = None,
    malformed_action: str = "CRASH_ON_SINGLE",
) -> None: ...
def get(key: str, default: Any = None) -> Any: ...
def set(key: str, value: Any) -> None: ...
def get_all() -> Dict[str, Any]: ...
