from typing import Any, Dict, Optional

from src.core.base import SnowflakeID
from ..models import Reaction, CustomEmoji


class ReactionProtocol:
    _db: Any = None
    _auth: Any = None
    _messaging: Any = None
    _servers: Any = None
    _relationships: Any = None
    _media: Any = None
    _config: Dict[str, Any] = {}

    def _get_timestamp(self) -> int: ...
    def _generate_id(self) -> int: ...
    def _user_exists(self, user_id: SnowflakeID) -> bool: ...

    def _get_message(self, message_id: SnowflakeID) -> Optional[Dict]: ...
    def _get_conversation(self, conversation_id: SnowflakeID) -> Optional[Dict]: ...
    def _get_unique_emoji_count(self, message_id: SnowflakeID) -> int: ...
    def _get_channel_for_conversation(
        self, conversation_id: SnowflakeID
    ) -> Optional[Dict]: ...

    def _row_to_reaction(self, row) -> Reaction: ...
    def _row_to_custom_emoji(self, row) -> CustomEmoji: ...

    def _is_participant(
        self, conversation_id: SnowflakeID, user_id: SnowflakeID
    ) -> bool: ...
    def _check_server_permission(
        self,
        user_id: SnowflakeID,
        server_id: SnowflakeID,
        channel_id: Optional[SnowflakeID] = None,
    ) -> bool: ...

    def _validate_emoji(self, emoji: str) -> tuple[bool, Optional[int], str]: ...
    def _validate_custom_emoji_for_server(
        self, custom_emoji_id: SnowflakeID, server_id: SnowflakeID
    ) -> bool: ...
    def _validate_emoji_name(self, name: str) -> str: ...
    def _check_emoji_limits(self, server_id: SnowflakeID, animated: bool) -> None: ...
